-- Create the table for Amalan Records
create table public.amalan_records (
  id bigint generated by default as identity primary key,
  student_name text not null,
  day integer not null,
  sholat_subuh text,
  sholat_dzuhur text,
  sholat_ashar text,
  sholat_maghrib text,
  sholat_isya text,
  sholat_tarawih text,
  sholat_dhuha boolean default false,
  infaq boolean default false,
  dzikir boolean default false,
  itikaf boolean default false,
  tausiyah_ustadz text,
  tausiyah_tema text,
  tausiyah_intisari text,
  quran_pages integer default 0,
  total_exp integer default 0,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  -- Add a unique constraint to prevent duplicate records for the same student on the same day
  constraint amalan_records_student_day_key unique (student_name, day)
);

-- Enable Row Level Security (RLS)
alter table public.amalan_records enable row level security;

-- Create a policy that allows anyone to read all records (for leaderboard)
create policy "Enable read access for all users"
on public.amalan_records for select
using (true);

-- Create a policy that allows anyone to insert/update records (since we don't have auth yet)
-- In a real app, you would restrict this to the authenticated user
create policy "Enable insert for all users"
on public.amalan_records for insert
with check (true);

create policy "Enable update for all users"
on public.amalan_records for update
using (true);

-- Create the table for Inquiry Submissions
create table public.inquiry_submissions (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  subject text not null,
  message text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table public.inquiry_submissions enable row level security;

-- Create a policy that allows anyone to insert submissions
create policy "Enable insert for all users"
on public.inquiry_submissions for insert
with check (true);

-- Create a policy that allows only authenticated users (admins) to view submissions
-- For now, we'll allow public read for demonstration, but in production this should be restricted
create policy "Enable read access for all users"
on public.inquiry_submissions for select
using (true);
